### ISSUE TITLE
REST API: shouldn't item creation result in HTTP 201 rather than HTTP 200?

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/imeji#1003]
I think the [Atom Publishing Protocol](http://bitworking.org/projects/atom/rfc5023.html#crwp) may be a good example to follow. Item creation results in a HTTP 201 response, including the URL of the newly created item as ``Location`` header.

**Comment by natasab** [comment]
The Item creation now responses with HTTP 201. The Location header is not added, as there is no single authoritative location for the item (one can provide both REST API or WEB representation of the item as a location. (agreed with @xrotwang in email communication). Please close this issue if it's acceptable.
