### ISSUE TITLE
Possible misspelling

### ISSUE THREAD

**Issue by Christian-Sc** [imeji-community/imeji#1007]
http://qa-imeji.mpdl.mpg.de/imeji/album/h_Zpm3czedm4P1WH/share
![teilen1](https://cloud.githubusercontent.com/assets/10435723/5646740/aa999926-967f-11e4-9d1f-6129da6090c6.jpg)

http://qa-imeji.mpdl.mpg.de/imeji/collection/jmsWF_K0gRtnXSXN/item/j5Nn8qccXsaQ1jJZ
![teilen2](https://cloud.githubusercontent.com/assets/10435723/5646763/ddc1358e-967f-11e4-94f3-ddeeafbb9637.jpg)

**Comment by bastienMPDL** [comment]
@schlender What do you think? Teile or teilen?

**Comment by schlender** [comment]
@bastienMPDL Teilen

**Comment by bastienMPDL** [comment]
Done
