### ISSUE TITLE
HTTP 500 instead of 404 for wrong image URL

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/imeji#1010]
Requesting an invalid file URL leads to HTTP 500 instead of HTTP 404:
```bash
robert@astroman:~$ curl -I http://edmond.mpdl.mpg.de/imeji/file/d2JGQRxO19XTOEXG/36/65/76/23-80fd-4953-bf68-4ae631d111d4/0/web/05952a09064414f3e54f19a689e97cf2.JPG
HTTP/1.1 500 Internal Server Error
Date: Wed, 07 Jan 2015 19:23:24 GMT
Server: Apache-Coyote/1.1
X-Powered-By: JSF/2.0
```

**Comment by natasab** [comment]
Works on development version, does not work on edmond (which has an older version of imeji).

**Comment by natasab** [comment]
If i change "edmond" with the development instance, i even get HTTP 200 OK - which is even worse..
So there are two aspects, one is the imeji web app, the other is the upcoming imeji rest API, which again has a bug, as it brings as response 400 Bad Request

**Comment by xrotwang** [comment]
Yes, returning HTTP 200 and a page that says "item not found" doesn't seem like a good idea:
```bash
robert@astroman:~$ curl -I http://dev-faces.mpdl.mpg.de/imeji/item/12343
HTTP/1.1 200 OK
```
The page does also say one has to login, though. So maybe HTTP 401/3 may be the correct response (although I'd vote for 404 even in this case).

**Comment by natasab** [comment]
Ticket will be closed, as it refers to fileUrl. ItemURL is partly resolved, but as pointed still redirects. Should be separate issue and resolution.
