### ISSUE TITLE
Thumbnail creation does not work for image/tiff

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/imeji#1012]
It seems as if creation of thumbnails and web resolution does not work for files of mimetype `image/tiff`:
```bash
robert@astroman:~$ curl -I edmond.mpdl.mpg.de/imeji/file/d2JGQRxO19XTOEXG/d3/d2/1a/4c-00bd-43de-b89c-d8158e3af037/0/original/d27e455e96719820ce50692ae0d24700.tif
HTTP/1.1 200 OK

robert@astroman:~$ curl -I edmond.mpdl.mpg.de/imeji/file/d2JGQRxO19XTOEXG/d3/d2/1a/4c-00bd-43de-b89c-d8158e3af037/0/thumbnail/d27e455e96719820ce50692ae0d24700.tif
HTTP/1.1 500 Internal Server Error
```

**Comment by bastienMPDL** [comment]
This seem to be a problem od edmond installation.
I tested it on dev server and it work:
http://dev-faces.mpdl.mpg.de/imeji/collection/xVkq7ovYUOGveQH2/item/eCOeVGN9BjteLns7
We use imagemagick for thumbnail creation. I'm not sure if it has been installed for Edmond. I will check.

**Comment by xrotwang** [comment]
Oh, this can be closed. Thumbnail creation does work, it's just that the thumbnail is not a tiff, but a jpeg.

**Comment by bastienMPDL** [comment]
Ok, thanks
