### ISSUE TITLE
Check uniqueness of md5 hash within collection on upload

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/imeji#1013]
The uploader should provide an option to check the uniqueness of md5 hashes of items within a collection. When working with large sets of files, previously curated by hand, this may be a better check than just looking at filenames.

**Comment by natasab** [comment]
If there is a property setting (new property created) there will be checking of md5 hash for duplicate within a collection based on the property value(true/false). 
if property is not provided at all, md5 hash will be checked by default.
