### ISSUE TITLE
the wrong link for uploaded item

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1014]
1, upload an item and then click the link of item
2. an error reported, the link of item is wrong

![linkuploadeditem](https://cloud.githubusercontent.com/assets/4938318/5721672/9e127d08-9b34-11e4-9c41-03d25252071c.PNG)

![falselinkuploadeditem](https://cloud.githubusercontent.com/assets/4938318/5721679/a594f4a2-9b34-11e4-8037-7d435aa88927.png)

**Comment by bastienMPDL** [comment]
done
