### ISSUE TITLE
Edit Item: edit publication throws exception

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1022]
1, edit item per REST API, add publication citation
2. refresh item metadata, the publication citation shows as publication
3. edit item per edit, change the publication
4. an internal error reported

**Comment by yaoyan** [comment]
right now, if I delete the publication uri, the field fo publication be removed, even the citation exist

**Comment by vmakarenko** [comment]
fixed

**Comment by yaoyan** [comment]
Besprechung mit Vlad, REST API und Imeji Präsentation sollen einheitlich bleiben, d.h. wenn Publikation URI leer ist, wird der gesamte Feld gelöscht.
