### ISSUE TITLE
Single Upload: Upload not working after autocomplete for person

### ISSUE THREAD

**Issue by bastienMPDL** [imeji-community/imeji#1027]
1: Select a collection with a metadata type person and Cone as vocabulary  
2: Select a file
3: Type the name of person and select one entry from the suggestion
4: The file is lost

Proposal: Metadata could be displayed only when the file has been uploaded.
Proposal 2: There is an option in plupload to upload a file automatically (and then avoid clicking on upload). That could be a good option to fix this issue and to avoid one click (select -> save, instead select -> upload -> save)

**Comment by cafefish** [comment]
done

**Comment by cafefish** [comment]
closes imeji-community/imeji#<1027>

**Comment by yaoyan** [comment]
the order of processing is changed now. Firstly, the file be selected and then uploaded. The metadata will be listed. After that the user can select a collection, enter metadata profil and save it. If after selecting collection the user to select a new file and then add cone person, the file is still lost. Talk with Lu: It is problem from softwar component,

**Comment by yaoyan** [comment]
closes imeji-community/imeji#
