### ISSUE TITLE
REST API: syntax validation of json file except status 400

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1033]
but in 

created item: 422
"error": {
    "code": "1422",
    "title": "Unprocessable Entity",
    "message": "1422-message",
    "exceptionReport": "A file must be uploaded, referenced or fetched from external location."
  }

edit item: 500
"error": {
    "code": "1500",
    "title": "Internal Server Error",
    "message": "1500-message",
    "exceptionReport": "java.lang.String cannot be cast to de.mpg.imeji.rest.to.ItemWithFileTO"
  }

**Comment by bastienMPDL** [comment]
For what method?

**Comment by yaoyan** [comment]
creat item: post,
edit item put

**Comment by yaoyan** [comment]
fixed
