### ISSUE TITLE
Edit Item: Leere Fehlermeldung Anzeige

### ISSUE THREAD

**Issue by bastienMPDL** [imeji-community/imeji#1037]
![screenshot-localhost 8443 2015-01-29 09-25-32](https://cloud.githubusercontent.com/assets/1352249/5954549/2316070c-a799-11e4-8563-6bdd38f3231d.png)

**Comment by schlender** [comment]
could give a short notice of your workflow?

**Comment by bastienMPDL** [comment]
Just try to upload a file which is not allowed (for isntance: .exe, .sh. .bin), then do upload.

**Comment by yaoyan** [comment]
the file with extension .exe, .sh .bin  can not be uploaded, the empty error message does not displayed. For other file type is still the same problem. a group discussion and specification be needed.
