### ISSUE TITLE
API: Documentation missing minimal examples

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/imeji#1047]
The API documentation should provide minimal examples, i.e. descriptions of the minimal amount of required information to make a request successful. Right now reverse engineering the required data to create a collection is a bit tedious.

**Comment by natasab** [comment]
Please check 

https://github.com/imeji-community/imeji/wiki

it would be great to share the editing of the API Doc where not yet finished, or accurate with the community. 
Feel free to add more ..

**Comment by xrotwang** [comment]
Actually, I did check. While I think community involvement is a good thing, in this case I would say, rather than let the community reverse engineer the API and then document this process, the API developers are in charge :)

**Comment by natasab** [comment]
Documentatino available 
https://github.com/imeji-community/imeji/wiki/A_Home-imeji-API-V1

If explicit example is missing somwehere then please add it as concrete issue.
