### ISSUE TITLE
API: Inconsistent implemnentation of Album members subresource

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/imeji#1050]
While I agree that batch operations to link and unlink members in an album could be useful, I still think the full set of CRUD operations should be available for each member of an album, i.e. there should be methods  

- `POST /albums/{aid}/members` to add a single item to an album,
- `GET|PUT|DELETE /albums/{aid}/members/{mid}` to retrieve, update, remove a member of an album.

While the main reason to have these methods now is consistency, I think they will be more important, once there is metadata associated with individual members, e.g. a comment, or album-specific tags for members (which I'm sure will be required at some point).

**Comment by natasab** [comment]
POST operation as suggested would assume there is a creation of a new resource (which is a member of an album, which has its own properties). With this in mind, POST/DELETE/PUT /members was intentionally avoided during the implementation of the current REST Api version.
.
If in future there would be a need to make comments for particular resource or album member, then there will be revision of the REST API with respective methods, and with "comments" Resource. At the moment, link/unlink is sufficient (for single or batch member add/remove).

**Comment by xrotwang** [comment]
I think whether internally a new resource is created or not is an implementation detail. To the client it definitely looks like one *is* created, namely an entity with the properties (foreign keys if you will) `collection ID` and `item ID`. So while I think the need for metadata associated with members is foreseeable, I still argue that even without this the API would be more consistent if it included the methods I'm asking for.

As far as I can see, this wouldn't even require changing the internal data model. The only additional information necessary to turn members into resources (from the perspective of clients) is an `id` and this doesn't need to be stored anywhere, because it can be computed, e.g. as concatenation of `album id` and `item id`.

So the only changes required would be the representation of `/albums/{id}/members`:
```python
[
    {
        'id': '<album-id>-<item-id>',
        'item': {<repr of the item>}
    }
]
```
and the same member representation would be used as body for `POST /albums/{id}/members`.

**Comment by xrotwang** [comment]
If my proposal would be accepted, it would even make the API for batch operations more consistent, I think. Instead of `link` and `unlink` one could have `PATCH /albums/{id}/members`.

**Comment by xrotwang** [comment]
Regarding the `PATCH` idea, you may want to look at https://www.mnot.net/blog/2012/09/05/patch and [rfc 6902](https://tools.ietf.org/html/rfc6902). Looking at http://jsonpatch.com/ this seems to be well supported, too.

**Comment by natasab** [comment]
PATCH certainly makes sense when it comes to partial update of a resource. But members are not official resource. If we provide according the suggestion the form

   'id': '<album-id>-<item-id>',

in GET

and then try to make consistent accordingly PUT, POST, DELETE, PATCH it would mean, there should be more modification e.g.

GET /albums/{id}/members/{member-id}
POST /albums/{id}/members
PUT /albums/{id}/members/{member-id} (?)
DELETE /albums/{id}/members/{member-id} (?)

which would impose the "member-id" is of form '<album-id>-<item-id>' ...

To confirm, the link/unlink was intenationally chosen (over PATCH, PUT/POST ...  which were also considered originally) in order to make it very clear for the client what it is doing (adding or removing members).

**Comment by xrotwang** [comment]
Ok. I see. I was just trying to point out how the API could be made a bit more future-proof. When I was thinking about what roles albums could play for my datasets, the use case I came across was as follows: In Tsammalex we collect images for biological taxa. Since we allow different ranks of taxa, we may want to link the same image to multiple taxa, say to the species *Panthera Leo* and to the family *Felidae* - but we would want the links to carry different tags. Thus, thinking about *members* as a proper sub-resource seems very natural to me.

**Comment by natasab** [comment]
Its a valid use case, but that can be done in some future implementation, wheres an album member has its own id and can be linked to labels, comments or other attributes. This scenario is at the moment not supported unfortunately.

**Comment by xrotwang** [comment]
I see. So the API will be versioned, then, I guess? Because implementation of the above would change the API in a backwards incompatible way.

**Comment by natasab** [comment]
I am closing this issue for the time being. API versioning mechanisms will be considered when the API v.1.0 is functionally finalized. In meantime, if it would be great if you share your thoughts about API versioning either as separate issue, or even better at the imeji.org blog, as a post.

**Comment by xrotwang** [comment]
Well, my thoughts are very simple: Just serve the API under a `/v1` path prefix to make sure you are not painting yourself into a corner.
