### ISSUE TITLE
API: Releasing an empty album is forbidden, but unlinking all members of a released album is ok.

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/imeji#1051]
The API is inconsistent in the following way: Trying to release an album with no members results in
```javascript
ERROR:pyimeji.api:got HTTP 422, expected HTTP 200
ERROR:pyimeji.api:{
  "error" : {
    "code" : "1422",
    "title" : "Unprocessable Entity",
    "message" : "1422-message",
    "exceptionReport" : "An empty album can not be released!"
  }
}
```
but unlinking all members of a released album is allowed. If there is no good reason to disallow release of empty albums (I don't know any), I'd vote for the simpler solution: allow release of empty albums.

**Comment by xrotwang** [comment]
I don't really understand why an empty released album is not allowed, considering the fact that unlinking items (except for the last one) from released albums is ok. If `RELEASED` is supposed to mean something like *will not change*, then clearly unlinking shouldn't be allowed at all. If on the other hand it is understood that released albums may change, what makes the last linked item any special?

Consider for example the use case *Album yearbook of ...*: Each year, all items of the album would be unlinked and the new collection will start. With the policy as implemented, this would mean I have to wait with unlinking until I have linked the first new item. This does not seem reasonable to me.

**Comment by bastienMPDL** [comment]
I must say that I agree with Robert.
We schould discuss about it together

**Comment by natasab** [comment]
Do not agree, sorry. That seems to me rather a use case for the sake of demonstrating the possibility. 
yearbooks are usually static aggregations, for one year. Once these are released items will stay inside. There could be though a case where some particular items should be removed for some particular reason.

If we had the case that an album is based on a query (and explicit querying criteria), thus its content is dynamically calculated - in that case i would agree, released album could be empty. 
The sole purpose of an Album is to have items inside - not to be empty.

**Comment by xrotwang** [comment]
Ok. I guess there can be different opinions on how to use an album. While I do agree that the purpose of an album is to be a container of items, I still think that at some point in time it may happen to have no items.

If both these opinions are judged as valid, wouldn't it make sense to make the code simpler by not enforcing one of these opinions within the system? I.e. less assumptions about the use cases and simpler code should make the case for removing these checks.

**Comment by xrotwang** [comment]
Thinking a bit more about it: The fact that albums may aggregate items which are not under the control of the album creator, already means that albums must be something volatile - even when released. Or should it be impossible to discard released items once they are linked to an album?

Anyway, without a clear and shared understanding of what release means for any component of the system, I'd always go for the simpler and more flexible option.

**Comment by natasab** [comment]
Current business rules are :
* An album may be empty when it has been pending or discarded.
*An album can not be released when it does not aggregate content (i.e. without items)

These business logic rules are implemented  in imeji software at MPDL (both in web app and in the REST API ).  

Until now, there has been no requirement to change this rule from business side (code should follow the rules in any case) . If there is a use case at some point which requires this modification, that means this would be updated not only in the API, but also in the web application. 

At the moment both are in sync - would vote for not doing any change unless indeed there is a strong reason with concrete priority use case for empty released albums (at least on MPDL side). (do not think code simplicity is a use case for end users :) 

Of course, if the community has this need then it can be contributed  by the community.

**Comment by natasab** [comment]
On the last comment: album only aggregates items which are explicitly selected by the album creator/editor.

**Comment by bastienMPDL** [comment]
The reason why I agree with Robert, is that I wouldn't guess what usage are going to be made with albums. 
Besides, as Robert mention it, we have anyway the problem that the pictures doesn't belong to the album. All pictures might be discarded by the actual picture owner and the album will appear empty.

**Comment by xrotwang** [comment]
@natasab I think it is a good idea to keep web-app and API in sync (I'd even go further and say ideally the web-app should use the API!). You say there was no request to change the rule of not allowing empty released albums. But was there one to actually implement that rule in the first place?

All I'm saying is, that when faced with two alternative implementations, simplicity and flexibility should win over complexity. And obviously, looking at this issue, my questions, and your [commit](https://github.com/MPDL-Innovations/imeji/commit/90e1a37664124e8266e595d4f2fa2fc4ca4de27f), your preferred implementation does increase complexity in terms of both, code and documentation (i.e. it has to be explained to users).

**Comment by natasab** [comment]
The mentioned commit only made the REST API in sync with web app. The comment in commit does state actually the same - if there is a need it should be changed. 

Yes, it may increased the complexity with 2 lines of code more, but it made it in sync with the web app. 

Do not know when this requirement originally appeared - it was implemented long time ago, and since then - there were obiously no changes required. 
Please feel free to change the code as wished.

**Comment by xrotwang** [comment]
@natasab I'm sorry if my comment on complexity came across as snarky. What I meant was simply that there is a cost to enforcing this rule; and this cost is both in terms of code and documentation. So I thought you might be happy to get rid of code (just as I am when I can shave off some lines from the client code), and get rid of a need to explain rules, that are not obvious to everyone (like me).

So are you actually ok with removing the rule to dis-allow empty released albums?

**Comment by natasab** [comment]
as stated already, if it is urgent high prio, would agree  - to disallow it one should change both the presentation check and validation rule in the release methods  . However, the whole album concept probably should be relaxed and rethought from several aspects,  so my preference would indeed be to do it in one go and consistently - there was somewhere additional requirement and discussion that album members should be considered as sub-resources on their own (own id, potentially own tags etc.) - with which i agree as well, but at the time it unfortunately not possible.

**Comment by xrotwang** [comment]
I see. In that case I would either remove album handling from the REST API, or have (and implement) a clear idea about API versioning. If the API will be versioned, this is something to consider and implement right now, because it will effect client development.
