### ISSUE TITLE
Collection List filter inconsistency

### ISSUE THREAD

**Issue by fsajp** [imeji-community/imeji#1054]
The following step will set Collection List filter by default "My (except discarded)".
1. Open imeji
2. Log in
3. Click on Collections to view Collection List

However, if the user run the step differently, Collection List filter will be by default "All":
1. Open imeji
2. Click on Collections to view Collection List 
3. Log in 

This default filter setting is confusing from user point of view. 
Since, Collection List should show all collection created by user and publicly published collections, we think the default filter should always be "All".

**Comment by natasab** [comment]
Thank you for this report.
In fact this the second case described is a quite a regular behavior. When a user is not logged-in, default collection filter is "All". 

When user is logges in, filter(query) does not change automatically, the list of collections is only extended with additional set of collections user has permissions to view. 

Agree its probably confusing, but when the user makes log-in, the collection he saw originally may not be in the list of "My" - thus this may be confusing as well.
Would some additional information on the screen be more useful?

**Comment by fsajp** [comment]
In order to avoid confusion, shouldn't the filter always be "All"?
Thus, if user perform steps Open Imeji, Log In and Click on Collections, he will see all collections he's allowed to see (Since, Collection List should show all collection created by user and publicly published collections, we think the default filter should always be "All").

**Comment by natasab** [comment]
Thank you, we are preparing usability study for Imeji, thus we will take this in consideration.
