### ISSUE TITLE
Default filename in Internet Explorer breaks Windows compressed folder

### ISSUE THREAD

**Issue by nabeta** [imeji-community/imeji#1056]
When uploading an item to imeji on our intranet using Internet Explorer, imeji uses its local path (C:\Users\Pubilc\...) as a filename. The problem is that Windows compressed folder cannot handle a zip file that contains such files.
For example, this collection contains two files. The filenames are "Penguins.jpg" and "C:\Users\Public\Pictures\Sample Pictures\Tulips.jpg".
http://imeji.nims.go.jp/imeji/collection/xmNIFgndJ2pWmR1

When I open a zip file of the collection with Windows compressed folder, only "Penguins.jpg" appears.

![imeji_filename](https://cloud.githubusercontent.com/assets/11428/7578888/a5938120-f896-11e4-8691-d2eb915ae57b.png)

The unzip command on Ubuntu 14.04 can extract two files with a warning message.

```sh
$ unzip NIMS\ imeji_Tue_May_12_11-01-31_JST_2015.zip
Archive:  NIMS imeji_Tue_May_12_11-01-31_JST_2015.zip
  inflating: Penguins.jpg
warning:  NIMS imeji_Tue_May_12_11-01-31_JST_2015.zip appears to use backslashes as path separators
  inflating: C:/Users/Public/Pictures/Sample Pictures/Tulips.jpg
```

I can change Internet Explorer settings to stop sending a local directory name,
https://jira.atlassian.com/browse/JSD-153

but I think imeji should remove the local directory name and use the base filename as an imeji filename by default.

I'm using Windows 7 and Internet Explorer 11. It may be related to #664 .

**Comment by bastienMPDL** [comment]
done
