### ISSUE TITLE
Edmond: remove the spot icon from edmond

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1066]
![spot_icon](https://cloud.githubusercontent.com/assets/4938318/8060576/7de5293a-0ec6-11e5-82ae-e060fc24ad97.PNG)
![spot_icon2](https://cloud.githubusercontent.com/assets/4938318/8060577/7e027e54-0ec6-11e5-8db1-00a6fcd99719.PNG)

**Comment by natasab** [comment]
resolved via https://github.com/MPDL-Innovations/imeji/issues/174
