### ISSUE TITLE
Edmond: Error message in "Upload"

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1068]
- the user has no collection in workspace
- the user try to upload a file
- an error message displayed "error_profile_labels_required", which the meaning of it is unclear
- the user upload a file, because of empty collection list, there is no collection for selection avaialbe
request
![error_upload](https://cloud.githubusercontent.com/assets/4938318/8061732/9d0f1018-0ecc-11e5-8633-2b3b8322c02e.PNG)
![nocollection_upload](https://cloud.githubusercontent.com/assets/4938318/8061731/9d00c562-0ecc-11e5-8b59-13eafe21bd6f.PNG)

: file should not be uploaded if there is no collection

**Comment by natasab** [comment]
This ticket has been resolved in development branch.
