### ISSUE TITLE
Edmond: (Metadata profile) be added in template list automatically after changing the copied profile name

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1072]
1. create a collection and copy a profile template
2. edit the profile, change profile name
3. save the changing
4. in the profile template list, a profile names "(Metadata profile)" created automatically

**Comment by bastienMPDL** [comment]
The problem occurs only when you try to create the collection without title.
The a profile is created with title "(Metadata profile)", but not the collection
