### ISSUE TITLE
Edmond: facet list is unchanged in collection created by no-admin-user and with default profil

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1073]
1. no admin-user created a collection and reference default profil 
2.  admin edit default profil and add some metadata
3. the facet list in collection with no-admin-user keep unchanged, the list in collection with admin user changed

**Comment by natasab** [comment]
See commit https://github.com/MPDL-Innovations/imeji/commit/3d465f04433f5c910735ec72127bb3f3b642a64b
