### ISSUE TITLE
Edmond: remove the profile template from collection information

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1074]
1. creat a collection without profile
2. edit the collection information
3. the profile list displayed

**Comment by natasab** [comment]
I do not understand this bug!

**Comment by natasab** [comment]
In general, if there is empty  profile for the collection which is not edited, the profile list should be provided, so that users can choose again.
Tis is not a bug.

**Comment by yaoyan** [comment]
problem are
1. if user do not want to edit profile at first and just only edit collection information, it is impossible to save the collection information without adding metadata profile
2. the option to select existed profile shoud be in field metadata profile, not in collection information

**Comment by bastienMPDL** [comment]
I checked, and I agreee: this is a bug.
If the collection has no profile, you can not edit the collection information because of this issue.

**Comment by natasab** [comment]
I see, on the Edit form, the "use a profile template" checkbox is not displayed. 
So it should be displayed and then we have same form as via creation of collection.

**Comment by natasab** [comment]
see referenced commit
