### ISSUE TITLE
Edmond: profile uri of collection with copied profile not valid after remove user admin rights

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1075]
1. an user as admin create a collection with copied profile
2. the user remove the admin rights
3. the profile uri is unvalid and change to: http://qa-edmond.mpdl.mpg.de/imeji/profile/ 
4. click on "http://qa-edmond.mpdl.mpg.de/imeji/profile/ ", 404 Error
5. try to delete collection: Error during deletion of the collection!

**Comment by vmakarenko** [comment]
I can confirm the problem or related issue (tested @ dev): 
1) create collection as user with admin privs + copy profile   
2) revoke admin priv from user itself
3) try upload file into the collection: error message like
.....................................................
1 Uploading of files failed:
    File DSC06195.JPG not uploaded: makarenko@mpdl.mpg.de not allowed to read http://dev-faces.mpdl.mpg.de/imeji/metadataProfile/2buKlfTJAu_h8Re0
.....................................................

**Comment by vmakarenko** [comment]
related to #1076
