### ISSUE TITLE
Edmond: User without right to create a collection can not upload file wthi single upload

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1079]
related to https://github.com/MPDL-Innovations/imeji/issues/172
1. login as user without right to create a collection
2. user has some collections with right "upload items"
3. go to single upload and upload a file
4. the collection list is empty

**Comment by bastienMPDL** [comment]
closing  (see commit above) for better overview of open issue

**Comment by natasab** [comment]
would suggest to test always not only on edmond, but on dev-faces as well, in order to check if issue appeared or not in the last version.

**Comment by yaoyan** [comment]
I can still reproduce in Dev

**Comment by natasab** [comment]
see referenced commit.
