### ISSUE TITLE
Edmond:  Hochladen einige Dateiformat ist gescheitert

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1080]
![jpegfile_upload](https://cloud.githubusercontent.com/assets/4938318/6803518/46f55104-d238-11e4-9242-c74bd8879330.PNG)

![fileformatnotaccepted](https://cloud.githubusercontent.com/assets/4938318/8110687/fa288f3a-105d-11e5-8add-72221163a006.PNG)

![fileformatnotaccepted2](https://cloud.githubusercontent.com/assets/4938318/8111156/7d957fa2-1060-11e5-8198-656c94480cd0.PNG)

**Comment by bastienMPDL** [comment]
Can you attached the files.
The error says "permission denied". Are you sure you are allowed to upload in this collection?

**Comment by natasab** [comment]
Hm... some of such pngpng or jpgjpg files i have seen as well on spot webapps directory..

**Comment by natasab** [comment]
can it have any relation to image magic?

**Comment by yaoyan** [comment]
some files 

![awob_setup](https://cloud.githubusercontent.com/assets/4938318/8156987/3b7f0018-1351-11e5-8cfb-616b3e915a8f.PNG)
![awoblogpublication](https://cloud.githubusercontent.com/assets/4938318/8156983/3b6f6f0e-1351-11e5-9a93-0a8b9bd72f95.PNG)
![awobmessages - kopie](https://cloud.githubusercontent.com/assets/4938318/8156984/3b7216f0-1351-11e5-86f3-1c4e0be2a981.PNG)
![awobpublication](https://cloud.githubusercontent.com/assets/4938318/8156985/3b74cb34-1351-11e5-801b-a8975f48a102.PNG)
![awobtasks - kopie](https://cloud.githubusercontent.com/assets/4938318/8156986/3b763a82-1351-11e5-9ca5-6fff94b42493.PNG)

**Comment by yaoyan** [comment]
its works fine in dev faces, but not in edmond. the configuration is the same

Configuration von dev faces:
![configuration_dev](https://cloud.githubusercontent.com/assets/4938318/8157135/82117712-1352-11e5-9808-5efc5dca0e47.PNG)

Configuration von edmond
![configuration_edmond](https://cloud.githubusercontent.com/assets/4938318/8157134/82034d68-1352-11e5-8e6f-7df7e67ce286.PNG)

**Comment by vmakarenko** [comment]
tested at qa-imeji and dev-faces, works fine. The problem is only presented on qa-edmond
