### ISSUE TITLE
Edmond:  user with upload file rights can not overwrite the orginal file

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1082]
1. user has rights to upload file in shared colletion
2. user upload a file and want to overwirte the original file 
3. error message: user not allowed to update the file
4. go back to item view, the original file is broken

![overwritefile](https://cloud.githubusercontent.com/assets/4938318/8110455/ac72e368-105c-11e5-8011-d5b9e2b30a2b.PNG)
![overwritefile2](https://cloud.githubusercontent.com/assets/4938318/8110454/ac610300-105c-11e5-9839-56cc56db0234.PNG)

**Comment by yaoyan** [comment]
Go th home page, the broken item with collection name showed in caroussel
![homeview](https://cloud.githubusercontent.com/assets/4938318/8110645/aa95062e-105d-11e5-99fe-80e39a8e8f32.PNG)

**Comment by vmakarenko** [comment]
Cannot reproduce on dev:
UPLOAD CONTENT interface, checked "Upload preview images..." and "Overwrite the original file...", upload already uploaded file (override the old one one).
Works fine.

**Comment by yaoyan** [comment]
- the collection should be shared to another user with rights to upload content
- the user upload content and check only "Overwrite the orginal file of an existing item"
- start upload and error message user not allowed to update content
Error in Dev and Edmond

Test files:
![apple](https://cloud.githubusercontent.com/assets/4938318/8209844/8232f388-150f-11e5-90ac-a6fb790ad7b1.png)

![apple](https://cloud.githubusercontent.com/assets/4938318/8209875/ad350968-150f-11e5-8b7e-2a4904f2bcc2.gif)

**Comment by vmakarenko** [comment]
Reproduced on dev

**Comment by vmakarenko** [comment]
Reason: not enough grants for file update for target user if only **Create Item** checked,  **Edit Item** should be checked as well.
Changed: 
* Options  section: "Overwrite the orginal file of an existing item" switched on hand of **Edit Item** Grant; * Share interface: Upload Items -> Create Items
