### ISSUE TITLE
Edmond: inconsistency item delete in released album

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1083]
related to: https://github.com/MPDL-Innovations/imeji/issues/144

1. Go to a released album where user have rights to view and add items
2. Select all items and click on remove from this album
3. warning message: Album is released! You are trying to remove all items from this album! Discard the album if necessary!
4. Click on remove all items from album beside All items
5. all items be removed

**Comment by natasab** [comment]
fixed, see commit https://github.com/MPDL-Innovations/imeji/commit/657377af968fdf7b0ef83c76098ebd6bcb667b6c

**Comment by yaoyan** [comment]
tested
