### ISSUE TITLE
Spot/Edmond: warning  message after releasing collection

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1084]
![warning_message](https://cloud.githubusercontent.com/assets/4938318/8161241/dfbe9a5c-1375-11e5-950e-395aecf13af2.PNG)
1. create a collection and upload an item
2. release it
3. a warning message reported: I can not get to the collection id

**Comment by natasab** [comment]
closed, see https://github.com/MPDL-Innovations/imeji/commit/fc371ee907141815c6fa3e1ead5375e0ab4b631b

**Comment by yaoyan** [comment]
tested
