### ISSUE TITLE
Dev/Edmond: "Remove all from album" in shared album

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1090]
1. user 1 add public and private items into album
2. user 1 shares the album to user 2 with rights to view album and add/remove items
3. user 2 go to album list and makes the album active
4. user 2 removes all items from album, which state is public
5. user 1 login and go to album, all items be remove (private and public)

https://github.com/MPDL-Collections/edmond/issues/40
https://github.com/MPDL-Innovations/imeji/issues/101

**Comment by bastienMPDL** [comment]
Please check if it is still the case.
The issue https://github.com/imeji-community/imeji/issues/1089 might have been related and the fix might have fix this issue as well.

**Comment by natasab** [comment]
tested on dev, issue is resolved.
a) When removing all items, only Items visible to user with the share are removed.

**Comment by yaoyan** [comment]
tested
