### ISSUE TITLE
Space: default metadata profile can not be loaded in collection creation

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1102]
![space_metadataprofile](https://cloud.githubusercontent.com/assets/4938318/8285619/c4c222fc-1904-11e5-873c-e62781603150.PNG)

**Comment by natasab** [comment]
https://github.com/MPDL-Innovations/imeji/commit/23359d0becce3ef63b610c7d9b2f95c6e03a4d47

**Comment by yaoyan** [comment]
tested
