### ISSUE TITLE
shared Collection, upload of images

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1107]
https://github.com/MPDL-Innovations/imeji/issues/104
the problem in single upload is not fixed
![upload](https://cloud.githubusercontent.com/assets/4938318/8310093/3ec57ec2-19ce-11e5-8bf3-a4cafb84140c.PNG)

**Comment by natasab** [comment]
Closed with 
https://github.com/imeji-community/imeji/issues/1097

**Comment by yaoyan** [comment]
can still reproduced, SNAPSHOT - build date 2015-06-24 11:44:48
