### ISSUE TITLE
Edmond: the scaling of space logo

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1108]
![space_logo](https://cloud.githubusercontent.com/assets/4938318/8310773/694e8b76-19d2-11e5-9e1c-4a921eb5828f.PNG)

**Comment by bastienMPDL** [comment]
@schlender can you check that?

**Comment by schlender** [comment]
@yaoyan 
what's the workflow for these behaviour?

I created a space with a vertical and a horizontal orientated picture and it was resized to the right dimensions. So I can't reproduce the effect.

**Comment by bastienMPDL** [comment]
Could not be reproduce
