### ISSUE TITLE
view technical metadata leads to internal server error

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#1112]
example file, file type:JPG

![awob_issuetype_stats](https://cloud.githubusercontent.com/assets/4938318/8329175/a9a043f4-1a77-11e5-888a-df252ac098e0.JPG)

**Comment by bastienMPDL** [comment]
Problem is coming with tika:
java.lang.ClassNotFoundException: com.drew.lang.RandomAccessReader
It seems there has been a problem during the compilation, since the problem doesn't appear locally and on spot. To be retested after a new deploy.

**Comment by bastienMPDL** [comment]
fixed via better dependency management
