### ISSUE TITLE
API: The docs do still mention the not implemented short metadata format

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/imeji#1116]
E.g. https://github.com/imeji-community/imeji/wiki/Items:-Create-new-item

**Comment by mpdl-innoteam** [comment]
@xrotwang : I do not see it , sorry.. there is content which is commented though, and is not visible unless you "edit" the page or you are seing the sources directly..

**Comment by natasab** [comment]
I see now, examples were different.
Modified.
