### ISSUE TITLE
API: generating list of all files uploaded before

### ISSUE THREAD

**Issue by ioverka** [imeji-community/imeji#1117]
Context: DokDisTool (MPDL Information)

For the automated file upload, we create a list of all files uploaded previously to distinguish which files can be loaded and which need to be updated instead. Currently, this process is pretty time and resource(?) consuming because the script has to request all items for all relevant collections (>90). 

Introducing a search by collectionId could improve the performance - and maybe this is already possible?

https://spot.mpdl.mpg.de:443/rest/items?q=(col%253D%253D%22http%253A%252F%252Fspot.mpdl.mpg.de%252Fcollection%252FfwXOOfjVViVN60Pp%22)%2BOR%2B(col%253D%253D%22http%253A%252F%252Fspot.mpdl.mpg.de%252Fcollection%252FjDGPV76o6BbL39Q8%22)

The double encoding looks a little bit weird though... is that the correct? What is the maximal length of the query string?

**Comment by natasab** [comment]
There is a REST interface which will list you the items of the collection..i.e. in your example 

https://spot.mpdl.mpg.de/rest/collections/jDGPV76o6BbL39Q8/items

see also 

https://github.com/imeji-community/imeji/wiki/Collections:-Get-collection-Items

**Comment by natasab** [comment]
@ioverka please confirm if this is still an issue for you, otherwise close it please.

**Comment by natasab** [comment]
closing this issue, as no further input was needed.
