### ISSUE TITLE
API: no validation for date elements

### ISSUE THREAD

**Issue by ioverka** [imeji-community/imeji#1120]
It looks like submitted values for md elements of type "date" are not validated to the full extend, i.e.

    {
        "value": {"date": "test"},
        "statementUri": "http://spot.mpdl.mpg.de/statement/LRXnDGUPUeiM83O0",
        "typeUri": "http://imeji.org/terms/metadata#date"
    }

returns: "1422, Invalid value provided for metadata of type Date (test...)" - but

    {
        "value": {"date": "20156"},
        "statementUri": "http://spot.mpdl.mpg.de/statement/LRXnDGUPUeiM83O0",
        "typeUri": "http://imeji.org/terms/metadata#date"
    }

works fine, see https://spot.mpdl.mpg.de/collection/Xme8ziI7M1YEMel/item/5Vq5Vp2Qpon_2ph

**Comment by natasab** [comment]
Hm... could not get to any validation which is working now on my local instance..
Checkng..

**Comment by natasab** [comment]
Resolved via 

https://github.com/MPDL-Innovations/spot/commit/78b53c955d021bacb6ebe8b69b6049e186ecc219

**Comment by natasab** [comment]
Issue has been fixed longer time ago.. I will close it asap.
