### ISSUE TITLE
"Default first Collection" wird automatisch mehrmals angelegt 

### ISSUE THREAD

**Issue by hofmannc** [imeji-community/imeji#1123]
Umgebung: 
http://qa-imeji.mpdl.mpg.de/collections?q= 
Nutzer: 
hofmann@mpdl.mpg.de
Beobachtung: 
Die Sammlung "Default first collection of Hofmann, Catherina" erschien beim ersten Zugang zum Account als einzige in der Auflistung. Im Laufe der Bearbeitungszeit wurden vom System aber vier weitere "Default first Collections" erzeugt (eine habe ich gelöscht).
Ziel: 
Die "Default first collection" sollte nur einmal erzeugt werden.

**Comment by bastiensaquet** [comment]
Kannst du es nochmal testen. Scheint gefixt zu sein

**Comment by hofmannc** [comment]
Ja, sieht so aus, seit 05.Oktober 14:22 wurde keine neue Default Collection mehr erzeugt.

**Comment by bastiensaquet** [comment]
Ich schiesse also
