### ISSUE TITLE
Fehlermeldung "error user organization unfilled" bei "Neue Sammlung anlegen"

### ISSUE THREAD

**Issue by hofmannc** [imeji-community/imeji#1124]
Umgebung:
http://qa-imeji.mpdl.mpg.de/createcollection?reset=1
Nutzer:
hofmann@mpdl.mpg.de
Getesteter Vorgang: "Neue Sammlung anlegen"
-> Sammlungen -> neu -> Titel: Testtesttest123
-> OU Name: MPDL (per Hand eingegeben oder per Dropdown Menü)
-> Speichern
-> Fehlermeldung (OU Feld nicht ausgefüllt) siehe Screenshot ![151005_error user orga unfilled](https://cloud.githubusercontent.com/assets/14921701/10330858/0abef18e-6cd1-11e5-86dc-c728d3bc15bf.jpg)
Beobachtung:  Sammlung wurde nicht angelegt  (auch, wenn über Start/Neu/Sammlungen gekommen)
 Im Laufe des Vormittags (05.10.) mehrmals probiert, es kam immer die gleiche Fehlermeldung.

Die Sammlung „Sammlung viele Metadaten“ konnte im Laufe des Nachmittags wieder angelegt werden, seit dem wird im Feld für die Organisation "Organization name not specified" standardmäßig angezeigt.

Ziel: ?

**Comment by bastiensaquet** [comment]
Kannst du es nochmal testen. Ich kann es nicht reproduzieren. Vielleicht wurde inzwischen gefixt.

**Comment by hofmannc** [comment]
Habe es nochmal auf qa-imeji getestet, da steht jetzt immer standardmäßig "Organization name not specified" im Organisationsnamen, und ich kann die Sammlung anlegen.
Auf QA-Edmond steht jetzt in meinem Account hofmann@mpdl.mpg.de immer MPDL vorausgefüllt und ich kann eine Sammlung anlegen.
-> Das Ziel "Sammlung anlegen" wird erreicht, bleibt die Frage, ob es wichtig ist, das mit dem automatischen "Organization name not specified" zu fixen.
