### ISSUE TITLE
Updating item fails

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/imeji#1125]
In the pyimeji session below an item is retrieved, then an update (of the unchanged item) via PUT is attempted, resulting in the error
> Cannot find { typeUri: http://imeji.org/terms/metadata#text , statementUri: http://edmond.mpdl.mpg.de/imeji/statement/xzEO9l8KFKAoFmUP} in profile: http://edmond.mpdl.mpg.de/imeji/metadataProfile/kM83bnICvFmqxNwU

The JSON sent to the server looks like
```python
{
    "status": "RELEASED", 
    "mimetype": "application/octet-stream", 
    "versionDate": "", 
    "collectionId": "d2JGQRxO19XTOEXG", 
    "webResolutionUrlUrl": "http://edmond.mpdl.mpg.de/imeji/file/d2JGQRxO19XTOEXG/b1/ea/8f/88-440b-4545-ac2b-2a1537b65590/0/web/8359cac4efaa6413fcdf437b92f43a67.jpg", 
    "discardComment": "", 
    "visibility": "PUBLIC", 
    "filename": "ed07598cd65ec91997e82ae47f999e16.jpg", 
    "metadata": {
        "note": "first", 
        "license": {
            "url": "http://creativecommons.org/licenses/by-nc-nd/4.0/", 
            "license": "Attribution-NonCommercial-NoDerivatives 4.0 International"
        }
    }, 
    "version": 0, 
    "modifiedBy": {
        "fullname": "Forkel, Robert", 
        "userId": "robert_forkel%40eva.mpg.de"
    }, 
    "modifiedDate": "2015-11-05T11:51:40 +0100", 
    "createdBy": {
        "fullname": "Forkel, Robert", 
        "userId": "robert_forkel%40eva.mpg.de"
    }, 
    "createdDate": "2015-07-13T17:25:15 +0200", 
    "checksumMd5": "ed07598cd65ec91997e82ae47f999e16", 
    "fileUrl": "http://edmond.mpdl.mpg.de/imeji/file/d2JGQRxO19XTOEXG/b1/ea/8f/88-440b-4545-ac2b-2a1537b65590/0/original/8359cac4efaa6413fcdf437b92f43a67.jpg", 
    "thumbnailUrl": "http://edmond.mpdl.mpg.de/imeji/file/d2JGQRxO19XTOEXG/b1/ea/8f/88-440b-4545-ac2b-2a1537b65590/0/thumbnail/8359cac4efaa6413fcdf437b92f43a67.jpg", 
    "id": "YmeuCcw2asa9cY07", 
    "fileSize": 198532
}
```

```python
>>> from pyimeji.api import Imeji
>>> c = Imeji()
>>> i = c.item('YmeuCcw2asa9cY07')
http://edmond.mpdl.mpg.de/imeji/rest/items/YmeuCcw2asa9cY07
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): edmond.mpdl.mpg.de
DEBUG:requests.packages.urllib3.connectionpool:"GET /imeji/rest/items/YmeuCcw2asa9cY07 HTTP/1.1" 200 1364
>>> i.metadata
{u'note': u'first', u'license': {u'url': u'http://creativecommons.org/licenses/by-nc-nd/4.0/', u'license': u'Attribution-NonCommercial-NoDerivatives 4.0 International'}}
>>> i.save()
http://edmond.mpdl.mpg.de/imeji/rest/items/YmeuCcw2asa9cY07
DEBUG:requests.packages.urllib3.connectionpool:"PUT /imeji/rest/items/YmeuCcw2asa9cY07 HTTP/1.1" 400 342
ERROR:pyimeji.api:got HTTP 400, expected HTTP 200
ERROR:pyimeji.api:{u'error': {u'message': u'1400-message', u'code': u'1400', u'exceptionReport': u'Cannot find { typeUri: http://imeji.org/terms/metadata#text , statementUri: http://edmond.mpdl.mpg.de/imeji/statement/xzEO9l8KFKAoFmUP} in profile: http://edmond.mpdl.mpg.de/imeji/metadataProfile/kM83bnICvFmqxNwU', u'title': u'Bad Request'}}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robert/venvs/pyimeji/pyimeji/pyimeji/resource.py", line 185, in save
    self._api._req(self._path(), **kw),
  File "/home/robert/venvs/pyimeji/pyimeji/pyimeji/api.py", line 108, in _req
    raise ImejiError('Unexpected HTTP status code', res)
pyimeji.api.ImejiError: Unexpected HTTP status code
```

**Comment by xrotwang** [comment]
Btw. this issue nicely illustrates that two alternative JSON serializations for metadata are not user-friendly: The error message apparently states that something in the metadata is missing, but does so in terms of the *raw* format. Since I posted metadata in the *default* format, I have no idea how to relate the error to my input.

**Comment by natasab** [comment]
hm... was working on similar issue from other aspects.. 
You are right about the raw/default formats, however, this is a validation error which comes when you try to update the item and probably has nothing to do with the format.

Message could be probably better provided. But in fact, the message is correct. You try to provide a metadata with 

"note": "first", 
        "license": {
            "url": "http://creativecommons.org/licenses/by-nc-nd/4.0/", 
            "license": "Attribution-NonCommercial-NoDerivatives 4.0 International"

whereas there is no "note" metadata (or a metadata with label note) in the metadata profile. Following metadata are allowed:

source, creator and license

(see http://edmond.mpdl.mpg.de/imeji/profile/kM83bnICvFmqxNwU)

**Comment by xrotwang** [comment]
@natasab At the time the update was attempted, there was a *note* field in the profile. Anyway, the point is that the item was not changed by me in any way, but failed to validate (presumably because the profile or the database changed). I think it is a **must** that the application makes sure items remain valid no matter what happens in the backend.

**Comment by bastiensaquet** [comment]
Issues is ow well understood. We will fix the unvalid data on edmond and ensure that it doesn't happen anymore: see https://github.com/MPDL-Innovations/spot/issues/334

**Comment by natasab** [comment]
@bastiensaquet , @xrotwang  is this issue still valid? Please close if not

**Comment by bastiensaquet** [comment]
Basically yes.
But I will close it after updating imeji on edmond (happening this week)
