### ISSUE TITLE
minor issue: German interface displayed, even supported languages are restricted to "en" via admin

### ISSUE THREAD

**Issue by ioverka** [imeji-community/imeji#1131]
Browser: Chrome, Version 48.0.2564.103
with "Spracheinstellung" set to "Deutsch (Deutschland)"
and no cookie

First request to imeji instance returns German interface. With this following cookie is set:

Name:	IMEJI_LANG
Content:	en
Domain:	outbox.mpdl.mpg.de
Pfad:	/
Senden für:	Jede Verbindungsart
Für Skript zugänglich:	Ja
Erstellt:	Montag, 8. Februar 2016 um 14:59:35
Läuft ab:	Dienstag, 7. Februar 2017 um 14:59:35

and all subsequent requests are delivered in English.

**Comment by bastiensaquet** [comment]
Could you find out what's happening here. I still xan not reprodude it.

**Comment by ioverka** [comment]
Do you ask me ;)? I saw this several times and some test users commented on it as well (e.g. Michael). It can be reproduced on every computer with a German browser installed:
1. delete the cookies
2. call the service homepage

**Comment by bastiensaquet** [comment]
Ok, thanks, Ill try again

**Comment by bastiensaquet** [comment]
@ioverka Can you test here: http://qa-edmond.mpdl.mpg.de/
It should be fixed

**Comment by ioverka** [comment]
Looks fine. I'm still able to reproduce the behavior on http://outbox.mpdl.mpg.de but not on http://qa-edmond.mpdl.mpg.de/. Thanks!
