### ISSUE TITLE
Add dummy picture for discarded images

### ISSUE THREAD

**Issue by rikeMPDL** [imeji-community/imeji#303]
As in: https://github.com/imeji-community/imeji/issues/111

**Comment by bastienMPDL** [comment]
As fas as I know, this is not implemented. For instance:
https://dev-faces.mpdl.mpg.de/imeji/collection/twjPSip80pieZlFy/item/VjYre3fnwC6PDYWN

**Comment by natasab** [comment]
Well it's probably the stylesheet, i see the image when i look better at it.

**Comment by bastienMPDL** [comment]
You are right... Goof eyes are needed!
I will ask Marco if he has an idea to improve it.
