### ISSUE TITLE
Keep Metadata Insert Box by Warning for Wrong Data

### ISSUE THREAD

**Issue by grossmannmpdl** [imeji-community/imeji#598]
After inserting "wrong" geo data (i.e. letters not digits) and saving, there is a warning sign (totally correct), but the metadata insert box is closing. It would be quite elegant for the user workflow, if this warning sign appears and the insert box is still open.
see also #529 
![imeji_insert_geodata_error](https://f.cloud.github.com/assets/5071889/1671623/390c0d02-5cbf-11e3-98dc-3f30e6d62ac9.png)

**Comment by bastienMPDL** [comment]
duplicate
