### ISSUE TITLE
Adding Validation rules on image editing page

### ISSUE THREAD

**Issue by cafefish** [imeji-community/imeji#637]
Adding Validation rules on server/client side, for
- geolocation: label input could be empty; if latitude/longitude is not empty, another value should be entered
- URI: validate input URI format, e.g. starts with http/https/ftp…
- Date: validate input date format, e.g. yyyy-mm-dd

etc.

**Comment by natasab** [comment]
should be tested, should work now for regular inserts, updates, should be tested for ingest.
