### ISSUE TITLE
an error reported after admin changes the user email adress

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#936]
1. login as admin
2. edit a user, change the email adress
3. an eror reported
![changeuseremail](https://cloud.githubusercontent.com/assets/4938318/3354671/ef57bcc0-faa6-11e3-936d-cf82e5c7b46f.JPG)

**Comment by bastienMPDL** [comment]
The user id mechanism has been changed.
We used the emails as id so far.
Now we generate an internal id, which solves the problem.
