### ISSUE TITLE
Rework wording of action links

### ISSUE THREAD

**Issue by kleinfe** [imeji-community/imeji#964]
"Wording(1): Wir schreiben „View Items“ „View Metadata“ „Upload item“. Würde es nicht reichen „Items“  „Metadata“  „Upload""

"Wording(3). Ich bin immer noch unzufrieden mit dem Label „Metadata“. Hat jemanden eine bessere Idee?"

**Comment by natasab** [comment]
Older issue, menu/icons and labeling reworked.
