### ISSUE TITLE
sub/sup tag in metadata

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#981]
sub/sup tag are not resolved in collection/album title, description in item list, metadata

**Comment by natasab** [comment]
Hm... i guess here it would be sensible to set-it-up on the level of the metadata profile element (if it's html-encoded or not) .. or we should provide this by default.. ?

**Comment by xrotwang** [comment]
If by "resolved" you mean rendered, I'd vote against such a behaviour. Unless it is clear that rendering of HTML will be limited to sub/sup tags, this would introduce quite a bit of complexity and surface area for vulnerabilities.

**Comment by natasab** [comment]
no requirements at present. closing this issue.
