### ISSUE TITLE
display size of image

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji#984]
currently the display size of image is different 

Collection Start Page
![imagedisplaysize_preview](https://cloud.githubusercontent.com/assets/4938318/4556261/305f310c-4ec7-11e4-9b62-474dc0618cd3.PNG)

Image list
![imagedisplaysize_imagelist](https://cloud.githubusercontent.com/assets/4938318/4556263/3991936e-4ec7-11e4-8999-46983852725c.PNG)

Detail View
![imagedisplaysize_detailview](https://cloud.githubusercontent.com/assets/4938318/4556269/442dfd6c-4ec7-11e4-8ad9-7813ed09642a.PNG)

**Comment by bastienMPDL** [comment]
Can you have a look, how to get the same size for the thumbnail on the startpage and in the browse list.
