### ISSUE TITLE
Link to user page does not work without cookie

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/imeji#994]
The link to the user page sent with the email for a new account (https://github.com/imeji-community/imeji/blob/develop/src/main/resources/messages_en.properties#L77) results in HTTP 500 when accessed without sending a cookie (e.g. when accessed through the email for the first time, or via ``curl``).

**Comment by bastienMPDL** [comment]
Can not reproduce.
I tried with curl as well, but got no 500.

**Comment by xrotwang** [comment]
It does work on `dev-faces` but fails on Edmond - so I guess it has been fixed somewhere in between ...
